
export const Data = [
    {id: 1, admin: false,content:"hi"},
    {id: 2, admin: true,content:"hello"},
    {id: 3, admin: false,content:"how are you?"},
    {id: 4, admin: true,content:"I am fine"},
    {id: 5, admin: false,content:"testing"},
    {id: 6, admin: true,content:"hello"},
    {id: 7, admin: false,content:"how are you?"},
    {id: 8, admin: true,content:"I am fine"},
    {id: 9, admin: false,content:"testing"},
    {id: 10, admin: true,content:"hello"},
    {id: 11, admin: false,content:"how are you?"},
    {id: 12, admin: true,content:"I am fine"},
    {id: 13, admin: false,content:"testing"},
    {id: 14, admin: true,content:"hello"},
    {id: 15, admin: false,content:"how are you?"},
    {id: 16, admin: true,content:"I am fine"},
    {id: 17, admin: false,content:"testing"},
    {id: 18, admin: true,content:"hello"},
    {id: 19, admin: false,content:"how are you?"},
    {id: 20, admin: true,content:"I am fine"},
    {id: 21, admin: false,content:"testing"},
    {id: 22, admin: true,content:"hello"},
    {id: 23, admin: false,content:"how are you?"},
    {id: 24, admin: true,content:"I am fine"},
    {id: 25, admin: false,content:"testing"}
  ]